### ISSUE TITLE
Could not log in to Salesforce.com: Error: certificate not trusted

### ISSUE THREAD

**Issue by harshal-gajare** [joeferraro/MavensMate-Atom#129]
I am trying to create a new project with MavensMate for Atom and I get the error message 

Could not log in to Salesforce.com: Error: certificate not trusted

I had a project successfully created earlier and it was working till last week when I started getting a internal server error on the create project screen. So, I uninstalled MM and reinstalled it today and now I am getting the above message. 

I am using 
Mac OSX 
Atom 0.169.0
MM 0.0.14

Below is what I see in the console log. Any help is appreciated.

 {"id":"7144e840-9a50-11e4-a280-19516ed41c55","complete":true,"error":"Could not log in to Salesforce.com: Error: certificate not trusted","stack":"Error: Could not log in to Salesforce.com: Error: certificate not trusted\n  at /Users/XXXX/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/sfdc-client.js:110:25\n  at Promise_then_rejected (/Users/XXXX/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:780:43)\n  at Promise_done_rejected (/Users/XXXX/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:862:26)\n  at Rejected_then [as then] (/Users/XXXX/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:1324:23)\n  at Rejected_dispatch [as dispatch] (/Users/XXXX/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:1312:23)\n  at Pending_become_eachMessage_task (/Users/XXXX/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:1370:30)\n  at flush (/Users/XXXX/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/node_modules/asap/asap.js:27:13)\n  at process._tickDomainCallback (node.js:417:11)\n"}

**Comment by surfous** [comment]
Yeah, I'm getting this now, too. I'm on Yosemite with MM 0.0.14, and Atom just self-updated to 0.170
It's been a while since I created a project, so Atom has updated a few times since then. 

Under Atom 169, an existing project was complaining about not having a password in the project settings, but the project settings looked to be using auth tokens instead of storing the password. I don't have this as I blew away the old project and was going to recreate it when I was confronted with the certificate error. 

My stack trace is similar to the OP's. Slightly different, though, so in case that gives a clue:

```
 {"id":"dd430590-9a91-11e4-8951-afb2e34c4158","complete":true,"error":"Could not log in to Salesforce.com: Error: certificate not trusted","stack":"Error: Could not log in to Salesforce.com: Error: certificate not trusted
  at /Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/sfdc-client.js:110:25
  at Promise_then_rejected (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:780:43)
  at Promise_done_rejected (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:862:26)
  at Rejected_then [as then] (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:1324:23)
  at Rejected_dispatch [as dispatch] (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:1312:23)
  at Pending_become_eachMessage_task (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/q.js:1370:30)
  at flush (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/q/node_modules/asap/asap.js:27:13)
  at process._tickDomainCallback (node.js:417:11)
"}
```

**Comment by DebGit** [comment]
Hi Joeferraro,

  Could be silly question but not sure how this issue is closed.Can you please help on how should i fix this in my editor?

**Comment by lydonb** [comment]
@DebGit - It looks like @joeferraro closed your issue because it was a duplicate of this issue you're now commenting on, which is still open. Follow this issue (you can hit the "Subscribe" button on the right of this page) to be notified when this issue is updated.

**Comment by DebGit** [comment]
@lydonb Ok..Thanks,.

**Comment by michaelhoefer** [comment]
Looks like this is happening for everybody now.  Bit of a bummer.  Don't want to go back to Sublime if I can help it.  Simple cert renewal issue?  Failed for me on atom 170 and still on latest 172.  No update to the atom-mm package that I can see...

**Comment by joeferraro** [comment]
no idea at the moment guys, sorry. any particular org/instance? are you using a custom domain?

**Comment by harshal-gajare** [comment]
@joeferraro I do have a org with a custom domain. I haven't tested with anything else. I can try with a new developer org. will let you know

**Comment by harshal-gajare** [comment]
I get the same message with a brand new developer org.

**Comment by joeferraro** [comment]
@harshal-gajare what version of OSX are you running?

**Comment by harshal-gajare** [comment]
@joeferraro I have Yosemite 10.10.1

**Comment by surfous** [comment]
Production & sandbox orgs. We do have a custom domain for our org as well, but I've tried with my non-custom vintage DE Org, and I get the same failure.

**Comment by joeferraro** [comment]
Unfortunately, I'm now able to reproduce after upgrading to Atom 0.170.0. This leads me to believe it's something specific to Atom. Will do some more digging, but for now the workaround would be to install an earlier version of Atom: https://github.com/atom/atom/releases/tag/v0.165.0

**Comment by harshal-gajare** [comment]
ok Thanks @joeferraro. I observed similar behavior as @surfous for a existing project if that might give you any pointers. The old project that was working gave a error of password missing in the .settings file and if I tried to go to edit project page it gave a Internal Server Error.

**Comment by joeferraro** [comment]
I'm pretty sure this has to do with Chrome 39, which was introduced in Atom 0.167.0 

https://github.com/atom/atom/releases/tag/v0.167.0

http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html

**Comment by joeferraro** [comment]
I can confirm that the current workaround is to revert to 0.166.0 of Atom (https://github.com/atom/atom/releases/tag/v0.165.0) until we can figure out how to handle the cert policy changes in Chrome 39

**Comment by surfous** [comment]
@joeferraro, yeah that does look pretty culpable. Salesforce is replacing all SHA-1 certs with SHA-256, but their timetable is no sooner than April 1 for sandboxes and August 1 for all instances:
https://help.salesforce.com/apex/HTViewSolution?urlname=HTTPS-Security-Certificate-Switch-from-SHA-1-to-SHA-256-hash-algorithms&language=en_US&elq_mid=8537&elq_cid=4734486

Hopefully Chrome will allow for making explicit exceptions.

**Comment by lydonb** [comment]
Thanks @joeferraro - confirmed that downloading Atom 166 fixed my issue. Unfortunately it looks like there's no way to disable the auto-update feature of Atom per this link: https://discuss.atom.io/t/is-there-an-easy-way-to-disable-atoms-auto-update-without-building-it-from-source/13346/12 so it might continually download the latest update every time you open Atom, but I've tested it and as long as you Command+Q to quit to use the Quit menu item it will not install the update.

**Comment by joeferraro** [comment]
Just a quick update, I have a workaround in place. Before I push a new version of the package, I'm implementing a number of other updates to address some of the deprecated selectors Atom introduced over the past few weeks (https://atom.io/docs/v0.169.0/upgrading/upgrading-your-ui-theme). Hoping to get it out tomorrow.

**Comment by harshal-gajare** [comment]
That's great to know . Appreciate your quick responses @joeferraro  and Thanks for MM for Atom, it has been a great tool for Salesforce development.

**Comment by mattisdada** [comment]
Hey Joe, would you be able to advise on what the work around was to fix this issue so we could apply the workaround locally before your next update?

**Comment by joeferraro** [comment]
add  `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'` to the top of `init` in `mavensmate.coffee`

**Comment by DebGit** [comment]
Thanks Joe..It worked..:-)

**Comment by joeferraro** [comment]
FYI, I've pushed v0.0.15 of the package which resolves several issues and starts the long arduous process of updating deprecated atom references: https://atom.io/packages/mavensmate-atom

**Comment by harshal-gajare** [comment]
It works. Thanks @joeferraro

**Comment by vrforce** [comment]
I was waiting for this. THANKS Joe!
