### ISSUE TITLE
implement new project from existing directory (import project)

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate-Atom#131]

**Comment by davescruggs** [comment]
Is this implemented yet, or a workaround?

**Comment by davescruggs** [comment]
Is this implemented yet, or is there a workaround?

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!

**Comment by joeferraro** [comment]
TODO: add command to commands.json
