### ISSUE TITLE
Workspace and other are missing from MavensMate package settings page

### ISSUE THREAD

**Issue by michaelhoefer** [joeferraro/MavensMate-Atom#135]
Ran a fresh install, multiple times today to be sure, of Atom 176.0 and MavensMate-Atom .15.

Result is the Settings page only has the various Grammar settings populated.  The Workspace (mm_workspace) and many other settings are missing.  The whole section is hidden.

![mavensmate-atom-settings](https://cloud.githubusercontent.com/assets/479449/5986656/d8f992fa-a8b6-11e4-9a6e-3d3c658f7f18.png)

**Comment by joeferraro** [comment]
- Is there anything in the Atom developer console? 
- Is there a `MavensMate-Atom` entry in `~/.atom/config.cson`?

**Comment by michaelhoefer** [comment]
Just this:

Failed to require the main module of 'MavensMate-Atom' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.

And running apm rebuild does not help.  I can't find any more details, yet, about which native module.  Note this is after deleting Atom.app, deleting ~/.atom, then installing Atom and then the MavensMate package.

One other note: if you run apm install MavensMate-Atom, you get version 0.14...which has the full settings file.  Something changed in 0.15 to apparently rely on a different version of some module.

**Comment by michaelhoefer** [comment]
Bit more unhelpful info: I nuked everything locally.  Removed Atom, removed ~/.atom, even removed external node and npm install and all other node modules (didn't have that many).  Same result.  I also compared package.json in the .14 and .15 and haven't seen anything obvious.

**Comment by michaelhoefer** [comment]
Ah, sorry, I ignored one of your questions: NO, there is no MavensMate-Atom entry in config.cson.

**Comment by michaelhoefer** [comment]
One other note.  Something is wrong with Atom or the MavensMate-Atom package w/r/t updates.  If you install v.14 (via the command line apm like I explained prior), then launch Atom and go to Updates, it does not pick up on the newer .15 version.  If you uninstall the package, then reinstall it, it finds v.15.

**Comment by michaelhoefer** [comment]
Alright Joe, I narrowed down the problem to stale Local Storage of incompatible dependencies, accidentally.

In an attempt to get more info I forced atom into dev mode in app/src/package.js: getIncompatibleNativeModules, line 788:

if (__false &&__ !atom.inDevMode()) {
789         try {
790           incompatibleNativeModules = ((_ref3 = JSON.parse(global.localStorage.getItem(localStorageKey))) != null ? _ref3 : {}).incompatibleNativeModules;
791         } catch (_error) {}
792         if (incompatibleNativeModules != null) {
793           return incompatibleNativeModules;
794         }
795       } 

It looks like in dev mode it forces a reload of dependencies.  So once I hacked package.js as above and reloaded, it fixed the problem permanently (or at least until it gets corrupted again).

So seems like an Atom issue, not MavensMate.  Closing this out.

**Comment by joeferraro** [comment]
oh my. ok, thanks @michaelhoefer for the detailed analysis!
