### ISSUE TITLE
Run Unit test (Empty?)

### ISSUE THREAD

**Issue by sMaDyK** [joeferraro/MavensMate-Atom#139]
Hi,

There are sometimes when I try to run a particular test, this doesn't exist for Mavensmate in ATOM.
However this file is in ATOM, and in others IDE as Sublime Text or Eclipse, or the most important thing, this test exists on Salesforce.
Instead of this test called 'X', Mavensmate displays another one which is called 'test' and when I try to execute it is empty.

Thanks

**Comment by joeferraro** [comment]
Closing until more information is provided
