### ISSUE TITLE
Question: Where is the setting for auto-compile?

### ISSUE THREAD

**Issue by seanhharrison** [joeferraro/MavensMate-Atom#143]
I always turn off auto-compile/deploy on save in Sublime but I'm not seeing that option in MM-Atom. Am I just missing it?

**Comment by joeferraro** [comment]
It doesn't look like it's implemented anywhere. I assume you're trying to toggle it off?

**Comment by seanhharrison** [comment]
Indeed

**Comment by seanhharrison** [comment]
Is this something nifty contributors can jump in and wire up?
