### ISSUE TITLE
Small correction to Install Instructions

### ISSUE THREAD

**Issue by AlwaysThinkin** [joeferraro/MavensMate-Atom#144]
Was just installing MM for Atom and noted that the path to installation is different than the ReadMe. Instead of:
 Open Atom > Preferences/Settings > Packages > Search for "MavensMate" > Install
it's now:
 Open Atom > Preferences/Settings > + Install > Search for "MavensMate" > Install

**Comment by joeferraro** [comment]
Luuuuke, hope all is well man. Care to make a PR? Otherwise, I'll just update myself.

**Comment by joeferraro** [comment]
appreciate it! https://github.com/joeferraro/MavensMate-Atom/pull/145
