### ISSUE TITLE
Actions executing twice

### ISSUE THREAD

**Issue by johnnyfreeman** [joeferraro/MavensMate-Atom#147]
I have a fresh install of MavensMate-Atom. Certain actions are executing twice. 

### Environment

* MavensMate-Atom version: `0.0.16`
* Atom version: `0.179.0`
* OS: `OS X Yosemite (10.10.2)`

### Problematic Actions

* Execute Apex
* Clean Project
* Refresh (file) From Server
* Start Logging

**NOTE:** There could be more. This is just what I can remember off the top of my head.

### Example

Click `MavensMate` -> `Execute Apex` -> `Execute Apex UI...`

##### Expected Result

One new tab opens with the Execute Apex page.

##### Actual Result

Two (duplicate) tabs open with the Execute Apex page for each.

**Comment by joeferraro** [comment]
We need more steps to reproduce.

**Comment by joeferraro** [comment]
i'm able to reproduce now: 

1. open atom without a project
2. use open project command to open a mavensmate project
3. actions are bound to the mavensmate object twice, causing behavior detailed in this ticket

**Comment by joeferraro** [comment]
0.0.19 attempts to resolve this issue

**Comment by joeferraro** [comment]
@johnnyfreeman can you re-test and close if resolved? thx

**Comment by johnnyfreeman** [comment]
Will do!

**Comment by johnnyfreeman** [comment]
@joeferraro Looks good to me! Thanks man.

**Comment by joeferraro** [comment]
:+1:

**Comment by johnnyfreeman** [comment]
I believe this bug is still lingering a bit... 

Right click on the content of a page, click any of the "Split ..." options. You should now have two tabs open for the same file. At this point, you'll notice the save action executes twice in the console. Since we are just saving one file, I believe this behavior is not what we want.

Additionally, when you close one of the tabs, you will still see the save action executing twice. So it seems like we are not deregistering events somewhere (or something to that effect).

**Comment by JohnDTheMaven** [comment]
For what it's worth, I am seeing the same behavior
