### ISSUE TITLE
Stuck on Initializing MavensMate project..

### ISSUE THREAD

**Issue by logontokartik** [joeferraro/MavensMate-Atom#151]
I upgraded to Atom 0.180 and now I am stuck on "initializing mavensmate project..." Please see the screenshot
![screen shot 2015-02-18 at 8 54 55 am](https://cloud.githubusercontent.com/assets/1240774/6248270/edb518ba-b74b-11e4-9420-1cd6231f4cfe.png)

**Comment by joeferraro** [comment]
0.0.19 attempts to resolve this issue

**Comment by joeferraro** [comment]
@logontokartik can you re-test?

**Comment by logontokartik** [comment]
The latest version fixed it.Thank you for the quick turnaround.
