### ISSUE TITLE
Uncaught TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by jdickertBHTP** [joeferraro/MavensMate-Atom#153]
[Enter steps to reproduce below:]

1. From Atom.io, select Mavensmate -> Project
2. Select Open Project and select the appropriate project
3. Select Mavensmate -> Project -> Compile Project
4. Click Yes on Dialog.

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.2
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.18

### Stack Trace

Uncaught TypeError: Cannot read property 'compile' of undefined

```
At /Users/jessedickert/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/commands/project/compile-project.js:19

TypeError: Cannot read property 'compile' of undefined
  at Command.execute (/Users/jessedickert/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/commands/project/compile-project.js:19:10)
  at [object Object].Client.executeCommand (/Users/jessedickert/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/client.js:225:26)
  at MavensMateCoreAdapter.executeCommand (/Users/jessedickert/.atom/packages/MavensMate-Atom/lib/mavensmate-core-adapter.coffee:152:13)
  at atom-workspace.<anonymous> (/Users/jessedickert/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:240:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:69:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -1:35.8 mavensmate:new-project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:30.3 mavensmate:edit-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:24.7 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:22.9 mavensmate:new-apex-class (ul.list-inline.tab-bar.inset-panel)
     -0:07.7 mavensmate:edit-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:02.0 mavensmate:compile-project (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/jessedickert/Documents/BHTP/MavensMate"
    ],
    "mm_panel_height": 96
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.18

# Dev
No dev packages
```

**Comment by magandrez** [comment]
Hi,

I also have the same problem. 

-Manuel

**Comment by joeferraro** [comment]
0.0.19 attempts to resolve this issue

**Comment by jdickertBHTP** [comment]
I will check out this issue once I am able to compile.

**Comment by jdickertBHTP** [comment]
Doesn't seem to have worked.  Atom Froze during the process and the deployment never started in my SFDC org.

**Comment by jdickertBHTP** [comment]
This is still an issue.  

Additional Information: 

After Opening Project, select MavensMate -> Project -> Compile Project

Compile starts within Atom:
![screen shot 2015-02-25 at 9 12 45 am](https://cloud.githubusercontent.com/assets/11069678/6373190/c649b69a-bcce-11e4-8379-090e2de521b2.png)

Then I get this:
![screen shot 2015-02-25 at 9 13 17 am](https://cloud.githubusercontent.com/assets/11069678/6373198/d6161e6a-bcce-11e4-93af-0a0d989e1521.png)

Then, no deployment happens within my Salesforce.com org.  Even when selecting "Keep Waiting" on the warning shown above. 

Hope this helps!

**Comment by joeferraro** [comment]
Hi, @jdickertBHTP, thanks for the update. I'm aware of this issue with compile project, specifically. I'm considering moving all command execution to node subprocesses because I've found the main Atom process can become bogged down for reasons that are likely deep within the Atom core.

**Comment by joeferraro** [comment]
I'm closing this particular issue because there is no longer a problem with the adapter not possessing a valid project instance (the original reported issue). you can follow the progress here: https://github.com/joeferraro/MavensMate-Atom/issues/159
