### ISSUE TITLE
Cannot read property 'sfdcClient' of undefined

### ISSUE THREAD

**Issue by agentgill** [joeferraro/MavensMate-Atom#155]
Getting the following error when trying to create new components

Cannot read property 'sfdcClient' of undefined

OS: Yosemite 10.2.2
Atom: 0.181
Mavens: 0.0.18

**Comment by jdickertBHTP** [comment]
I got the same error when attempting to create a new Visualforce Page.

Atom Version: 0.181.0
System: Mac OS X 10.10.2
![screen shot 2015-02-20 at 7 45 07 am](https://cloud.githubusercontent.com/assets/11069678/6287138/aae53e04-b8d4-11e4-9ba4-8c7f0a47e9f2.png)

**Comment by joeferraro** [comment]
thanks for the report guys, unfortunately, atom development is "moving fast and breaking things" – faster than I can keep up. The way plugins determine a project's path has changed in a recent release. I'll be pushing a fix very soon.

**Comment by joeferraro** [comment]
0.0.19 attempts to resolve this issue

**Comment by joeferraro** [comment]
hey guys can you re-test at your earliest convenience?

**Comment by jdickertBHTP** [comment]
Tested:  I was able to create the Visualforce Page, but I get another error after successful creation.  It does appear that the VF Page is created successfully though.  

![screen shot 2015-02-22 at 8 34 35 am](https://cloud.githubusercontent.com/assets/11069678/6318901/d1b349fa-ba6d-11e4-8f76-e4d8420456b0.png)

**Comment by joeferraro** [comment]
OK, that's an atom issue, so closing this
