### ISSUE TITLE
Atom.io Mavensmate don't have "Project" Level Refresh from Server

### ISSUE THREAD

**Issue by arpanvpatel** [joeferraro/MavensMate-Atom#156]
I am just wondering if Mavensmate have "Refresh from Server" on Project Level.
In Sublime Text, i am able to refresh through
Sidebar -> Select 'Project' folder and right click -> MavensMate -> Refresh from Server
But in Atom, i am getting only MavensMate -> Delete from Server.
I have a file level Refresh from Server Option so, i can able to refresh file but no Option on Project level, So, i am not able to refresh my project from server.
You can see in below image:

![screen shot 2015-02-20 at 1 52 42 pm](https://cloud.githubusercontent.com/assets/11077969/6308209/cbb9b8ac-b907-11e4-98dd-d2ae4d60e647.png)

**Comment by joeferraro** [comment]
you can run the clean project command

**Comment by venkatpolisetti** [comment]
I really like the file level refresh as it is provided for Sublime Text. Our project is big and to clean it from Atom or update it from Mavensmate desktop takes a lot of time. I wish file level refresh comes to Atom too.

**Comment by oghg** [comment]
Totally agree with venkatpolisetti, would great to have the same refresh capabilities in Atom as in sublime.
