### ISSUE TITLE
Compile Failure with No Error Message

### ISSUE THREAD

**Issue by mfilpus** [joeferraro/MavensMate-Atom#161]
Trying to save some VisualForce pages, I'm getting a compilation failure, but no error message is displayed. Some pages work fine, and others are returning this:

![image](https://cloud.githubusercontent.com/assets/4072443/6489582/6349e08e-c26d-11e4-96e2-033a5538f1d5.png)

Here is the result:

{
  "result": {
    "checkOnly": false,
    "completedDate": "",
    "createdBy": "",
    "createdByName": "",
    "createdDate": "",
    "details": {
      "componentSuccesses": [],
      "runTestResult": {
        "numFailures": "0",
        "numTestsRun": "0",
        "totalTime": "0.0"
      },
      "componentFailures": [
        {
          "attributes": {
            "type": "ContainerAsyncRequest",
            "url": "/services/data/v32.0/tooling/sobjects/ContainerAsyncRequest/1dr17000000QJ3fAAG"
          },
          "Id": "1dr17000000QJ3fAAG",
          "MetadataContainerId": "1dc170000009G4lAAE",
          "MetadataContainerMemberId": null,
          "State": "Failed",
          "IsCheckOnly": false,
          "DeployDetails": {
            "allComponentMessages": [
              {
                "changed": false,
                "columnNumber": -1,
                "componentType": "ApexPage",
                "created": false,
                "createdDate": "2015-03-04T17:50:57.156+0000",
                "deleted": false,
                "fileName": "BITool",
                "forPackageManifestFile": false,
                "fullName": "BITool",
                "id": "066170000004Wk3AAE",
                "knownPackagingProblem": false,
                "lineNumber": 1,
                "problem": null,
                "problemType": null,
                "requiresProductionTestRun": false,
                "success": false,
                "warning": false
              }
            ],
            "componentFailures": [
              {
                "changed": false,
                "columnNumber": -1,
                "componentType": "ApexPage",
                "created": false,
                "createdDate": "2015-03-04T17:50:57.156+0000",
                "deleted": false,
                "fileName": "BITool.page",
                "forPackageManifestFile": false,
                "fullName": "BITool",
                "id": "066170000004Wk3AAE",
                "knownPackagingProblem": false,
                "lineNumber": 1,
                "problem": null,
                "problemType": null,
                "requiresProductionTestRun": false,
                "success": false,
                "warning": false,
                "filePath": "C:\\Users\\Mark\\Atom IDE\\Innovate Dev 2 Sandbox\\src\\pages\\BITool.page"
              }
            ],
            "componentSuccesses": [],
            "runTestResult": null
          },
          "ErrorMsg": null
        }
      ]
    },
    "done": false,
    "id": "",
    "ignoreWarnings": false,
    "lastModifiedDate": "",
    "numberComponentErrors": 1,
    "numberComponentsDeployed": 0,
    "numberComponentsTotal": 0,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": false,
    "runTestsEnabled": "false",
    "startDate": "",
    "status": "",
    "success": false
  },
  "promiseId": "01ebfa50-c297-11e4-8a7e-092782844a2e"
}

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
