### ISSUE TITLE
Unable to Connect to Blitz Environment

### ISSUE THREAD

**Issue by nihunt** [joeferraro/MavensMate-Atom#163]
I have been using MavensMate for Sublime text for development in a Blitz environment.  I copied the same exact settings from my Sublime config to Atom and cannot seem to connect.  I am using the custom URL set to: https://login-blitz04.soma.salesforce.com and have my Security Token in my password as well.

I am getting the following error: "Could not log in to Salesforce.com: Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out."

Is this a known bug?

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
