### ISSUE TITLE
MavensMate hang when compiling a single Apex class

### ISSUE THREAD

**Issue by magandrez** [joeferraro/MavensMate-Atom#164]
Hi,

I recently switched to MavensMate-Atom. I work on OS X Mavericks (10.10) with Atom 0.186 and MavensMate-Atom 0.0.20.

Saving a class file prompts MavensMate to compile the class. File is successfully saved (if I git status the project I see the change), however, the IDE never stops compiling and does not give any error whatsoever and as a result, the file is not uploaded to Salesforce (!).

The steps to reproduce the error...create a project, checkout some metadata from Salesforce sandbox org, modify it and save it. Changes are not visible in Salesforce org (sandbox, of course).

-Manuel

**Comment by magandrez** [comment]
I also noticed that a new file named tmp.zip is created in the root of the project, I believe it is come compilation temporary file, MavensMate never stops compiling, so the temporary file remains there and I cannot have access to open it. It throws this error:

```Reading the archive file failed: Offset is out of bounds```

**Comment by magandrez** [comment]
Couldn't reproduce the error, and now with last update of Atom, the environment seems to work and saves and compiles the code.

**Comment by ritsnuno** [comment]
Hello!
I'm experiencing the same issue.

I'm on a Mac El Capitan 10.11.6 with Atom 1.12.2 and the Mavensmate-Atom 1.0.9. All updated.

Although it saves to the org, it just keeps compiling and shows no error or other kind of message.

Does anybody has the same issue? 

Thanks!
