### ISSUE TITLE
Apex auto complete not working

### ISSUE THREAD

**Issue by Nivg** [joeferraro/MavensMate-Atom#166]
Hi,

I am using MM for Sublime for almost a year now, and used to the auto code complete when writing Apex code. In Atom the Visualforce auto complete is working but in Apex class I get only auto complete for primitive types, not for methods (like String methods).

If it's something not yet implemented please direct me to the right place (maybe autocomplete plus package) so I may help in this task.

Thanks,
Niv

**Comment by mh2292** [comment]
I can verify this as well.

**Comment by donaldrivard** [comment]
Not working for me either.

**Comment by joeferraro** [comment]
This is not yet a feature

**Comment by donaldrivard** [comment]
Thanks Joe for the update!
