### ISSUE TITLE
Can't Clean Project - EPERM, operation not permitted

### ISSUE THREAD

**Issue by mginou** [joeferraro/MavensMate-Atom#170]
Everytime I try to execute Clean Project it throws a operation not permitted error. Since I had just finished creating the project folder via MavensMate's New Project dialog, it seems unlikely to be a file permission issue.

Note that the referenced path (...test2\\src) actually doesn't exist, just an unpackaged directory (i.e. it looks like the clean got far enough to remove the src folder)

    Cleaning project
    > Could not clean project
    {
      "result": "Could not clean project",
      "error": "EPERM, operation not permitted 'c:\\Users\\mginou\\workspace\\test2\\src'",
      "stack": "Error: EPERM, operation not permitted 'c:\\Users\\mginou\\workspace\\test2\\src'\n  at Error (native)\n  at Object.fs.renameSync (fs.js:639:18)\n  at C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\lib\\mavensmate\\project.js:376:14\n  at tryCatch1 (C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\util.js:45:21)\n  at Promise._callHandler (C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:571:13)\n  at Promise._settlePromiseFromHandler (C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:581:18)\n  at Promise._settlePromiseAt (C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:733:18)\n  at Promise._settlePromises (C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:845:14)\n  at Async._consumeFunctionBuffer (C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:85:12)\n  at Async.consumeFunctionBuffer (C:\\Users\\mginou\\.atom\\packages\\MavensMate-Atom\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:40:14)\n  at process._tickCallback (node.js:366:11)\n",
      "promiseId": "593764c0-c832-11e4-b591-ed89d7e9b426"
    }

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
