### ISSUE TITLE
option to setup new static resource bundle should only be available for zip files

### ISSUE THREAD

**Issue by ImJohnMDaniel** [joeferraro/MavensMate-Atom#176]
On any given static resource, the option to setup new "static resource bundle" should only be available for zip file based static resources.  The option does not make sense when the static resource is text or image based.  I would suggest making the option only available for static resources whose content type is "application/zip"

**Comment by joeferraro** [comment]
unfortunately, atom does not support the ability to scope commands at this time (like ST does). closing until that becomes available
