### ISSUE TITLE
"compile" keybinding does noting

### ISSUE THREAD

**Issue by mh2292** [joeferraro/MavensMate-Atom#177]
Pressing 'ctrl+alt+s" (or whatever the configured keybinding is) to compile does not do anything. I have verified that the keybinding is working correctly using the key binding resolver, but nothing happens when i press the appropriate key combination.
The only workaround right now is to run mavensmate:compile from the command palette.

**Comment by kicker78** [comment]
I believe that the keymap is looking for the mavensmate:compile command when it should be looking for compile-file?
