### ISSUE TITLE
Cannot Goto Error in Compile Error View

### ISSUE THREAD

**Issue by zhufengjack** [joeferraro/MavensMate-Atom#185]
in Compile Error window, I want to click the error message to go to the line which error happen. But in it shows "Cannot Goto Class xxxxxxxxx
![screen shot 2015-04-22 at 01 34 23](https://cloud.githubusercontent.com/assets/1510216/7258524/c8f0ed04-e88f-11e4-97d0-9330e236deea.png)

"

**Comment by zhufengjack** [comment]
Any comments here

**Comment by joeferraro** [comment]
@zhufengjack are you still experiencing this issue in v1.0.0?

**Comment by zhufengjack** [comment]
@joeferraro  Yes. 
<img width="1272" alt="screen shot 2015-10-09 at 18 39 56" src="https://cloud.githubusercontent.com/assets/1510216/10391950/3dc4aba6-6eb5-11e5-8d76-37851ede0cf6.png">

**Comment by zhufengjack** [comment]
@joeferraro  I update to v1.0,6. But this issue still exist
<img width="1026" alt="screen shot 2015-10-09 at 18 42 47" src="https://cloud.githubusercontent.com/assets/1510216/10391984/a331f3f4-6eb5-11e5-9e41-df18737adb22.png">
