### ISSUE TITLE
Error message: Module version mismatch. Expected 43, got 41. (Mac OSX Yosemite, Atom 0.196.0, MM 0.0.20)

### ISSUE THREAD

**Issue by chrishickman81** [joeferraro/MavensMate-Atom#189]
The following packages could not be loaded because they contain native modules that aren't compatible with this version of Atom.

Previous Atom versions shipped with Chrome 31 and Node 0.11.10 but Atom now ships with Chrome 41.0.2272.76 and Node 1.5.1.

The packages listed should now ship versions of these native modules that are compatible with Node 1.5.1.

Updates for these packages may already be available that resolve this issue.

If no update is available you may want to notify the package author that their package isn't supported in Atom 0.196.0 because of the Chrome 41.0.2272.76 and Node 1.5.1 upgrade.

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
