### ISSUE TITLE
Apex Test Runner UI isn't returning results

### ISSUE THREAD

**Issue by ChristianLinenko** [joeferraro/MavensMate-Atom#195]
Hey guys,

When I launch the Apex Test Runner UI, it churns and churns and never returns a result. When I log into developer console in my org I can see that the test has completed, but the test runner UI inside of MM in Atom, is still up and running. 

Any ideas what that could be?

Thanks so much,

Christian

**Comment by dsharrison** [comment]
I have noticed that Mavensmate increases its polling interval the longer your tests are running. Out of curiosity, how long have you been waiting after you see the test finish in the Salesforce Deployment window?

**Comment by ChristianLinenko** [comment]
Not very long. Maybe 30 seconds or so. Our org is very big (2.6 million characters).
