### ISSUE TITLE
ERROR System keychain service not supported

### ISSUE THREAD

**Issue by GradyD** [joeferraro/MavensMate-Atom#198]
When trying to deploy to server I get System keychain service not support error.

I am on windows 8.1, how can I fix this?

**Comment by Georrgi** [comment]
I have the same problem. Any ideas?

**Comment by azothForgotten** [comment]
I have the same issue. I even tried disabling the System keyring flag, but the issue still crops up.

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
