### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [joeferraro/MavensMate-Atom#199]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.0.20`) of this package:

1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
1. If you would like your pane item with class `<ClassName>` to support modified behavior, please implement a `::onDidChangeModified()` method. If not, ignore this message. `::on` methods for items are no longer supported.
1. If you would like your pane item with class `<ClassName>` to support title change behavior, please implement a `::onDidChangeTitle()` method. `::on` methods for items are no longer supported. If not, ignore this message.
1. Pane item with class `<ClassName>` should implement `::getURI` instead of `::getUri`.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by joeferraro** [comment]
I addressed 1 & 4 and do not need the functionality described in 2 or 3. @benogle can you confirm whether the 2 attached commits address this issue?

**Comment by benogle** [comment]
Seems like they should be fixed :+1:

**Comment by joeferraro** [comment]
cheers, @benogle
