### ISSUE TITLE
Password stored as plain text

### ISSUE THREAD

**Issue by GradyD** [joeferraro/MavensMate-Atom#209]
In the config file there is a file called .settings and my password is displayed as plain text. This is a huge security risk. 

Is there a reason that the password can not be stored securely?

**Comment by joeferraro** [comment]
most likely because either 1) you're running windows and don't have the prerequisites to properly install `node-keytar` or 2) you have `Use keyring` set to `false`, otherwise the password is stored securely in the machine's keychain and retrieved by mavensmate when necessary.

![settings_-_atom](https://cloud.githubusercontent.com/assets/54157/8138256/32d7a6c2-1117-11e5-9d51-61e64a29211b.png)

**Comment by GradyD** [comment]
Thanks for the quick response. I am on windows so I do not have the concept of a key ring. 

I took on this project and the primary node package and I am not seeing anything for node-keytar. Can you point me to the docs on that?

**Comment by joeferraro** [comment]
sure you do, Credential Manager: http://windows.microsoft.com/en-us/windows7/what-is-credential-manager

https://github.com/atom/node-keytar

**Comment by GradyD** [comment]
I assume for keytar I just need to install as a global node module and it will be able to take advantage of it?

**Comment by joeferraro** [comment]
as long as it's on your PATH, MavensMate should be able to access it

**Comment by joeferraro** [comment]
keytar is an optional dependency in MavensMate's core: https://github.com/joeferraro/MavensMate/blob/master/package.json#L81. It's likely that running `npm install mavensmate` will yield some useful debugging information for why `keytar` is not being installed properly.

**Comment by GradyD** [comment]
Ok, thanks again for the quick responses! 

On windows 7 64 bit I had use keyring checked (it was checked by default) but the password was still saved in the file. This could be blocked by something the IT team has done on the company computers with a GPO or something. 

I also ran `npm install mavensmate` and it encountered an error because python was not found so node-gyp could not be found to compile the module. 

Now that I understand the reasoning I feel much better, thanks!

**Comment by joeferraro** [comment]
> I also ran npm install mavensmate and it encountered an error because python was not found so node-gyp could not be found to compile the module.

This is why it's failing to install `keytar`. Certain node modules, like `keytar` require platform-specific bindings. `node-gyp` makes this easy to do, but it does require python.
