### ISSUE TITLE
Symbols view (CMD+R) doesn't show any symbols.

### ISSUE THREAD

**Issue by DavinCasey** [joeferraro/MavensMate-Atom#218]
I've just installed Atom 1.0 with MavensMate-Atom 0.024.

Symbols View (CMD+R) worked perfectly in ST3 but I can't get it working in Atom.

This is on Mac OSX 10.10.2, Java 8 update 45.

Let me know if you need any more info to debug the issue.

**Comment by AccentureDavin** [comment]
Just checked and this bug is still present in MavensMate-Atom 1.0.3.

**Comment by joeferraro** [comment]
yes unfortunately, this has to do with the Atom symbols view package, which depends on ctags (http://ctags.sourceforge.net/). ctags does not natively support Apex.

**Comment by AccentureDavin** [comment]
I found this package: https://atom.io/packages/goto

It seems (at first glance) to work well with Apex.

**Comment by joeferraro** [comment]
thanks @AccentureDavin :+1:

**Comment by AccentureDavin** [comment]
No worries, hopefully you can roll it into the next release or into the installation instructions at least.

**Comment by silver-mx** [comment]
Hi, I am trying to use  https://atom.io/packages/goto, but it gets idle when executing 'Go to declaration'. Do you get the same behavior @AccentureDavin? Has anyone another alternative? @joeferraro any how this could be solved?

**Comment by silver-mx** [comment]
Nevermind @AccentureDavin https://atom.io/packages/goto takes a while to index everything I think. it worked after a while.

**Comment by mdemin914** [comment]
Goto seems to work! Thanks.
