### ISSUE TITLE
Test runner error: Could not run tests: undefined is not a function

### ISSUE THREAD

**Issue by AccentureDavin** [joeferraro/MavensMate-Atom#219]
Atom 1.0 with MavensMate-Atom 0.024, this is on Mac OSX 10.10.2, Java 8 update 45.

Steps to reproduce:

Open Apex Test Runner UI -> Select some test classes to run -> Run

Checking the setup menu in Salesforce shows that the tests did run as expected.

**Comment by jeancdc** [comment]
+1

**Comment by azothForgotten** [comment]
I'm having this issue on Windows 10

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
