### ISSUE TITLE
INVALID_OPERATION: No zip file content passed in

### ISSUE THREAD

**Issue by camfed** [joeferraro/MavensMate-Atom#224]
When trying to create a VisualForce page i'm getting this error no matter what option I select

**Comment by jeancdc** [comment]
I got it too.

**Comment by danwatt** [comment]
I am getting this error when saving a .resource file. package.xml - version 34.0, Mavensmate settings set to 34.0 as well.

**Comment by shnickburton** [comment]
I have changed my api version to 32.0, like the other similar bug suggested, but I still get this error when attempting to create any meta data(visualforce page, apex class, etc). Let me know if any specific output would be helpful.

**Comment by lydonb** [comment]
Looks like a temporary fix has been identified here:
https://github.com/jsforce/jsforce/issues/241

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
