### ISSUE TITLE
Resource Bundle deploy not available

### ISSUE THREAD

**Issue by aluukka** [joeferraro/MavensMate-Atom#235]
Hi, 

I'm trying to deploy a Resource Bundle to the server and the only available option the the menu is 'delete from server'

OSX 10.10.4 Atom 1.0.7 Mavensmate 0.0.24

**Comment by aluukka** [comment]
apparently something was changed in Atom. I reverted back to 1.0.6 and it's working again

**Comment by nathanKramer** [comment]
I have this problem as well. 
When using the Deploy Resource Bundle option in the context menu, the usual dropdown to select the appropriate resource bundle never appears.

OSX 10.10.1
Atom 1.07
Mavensmate 0.0.24

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
