### ISSUE TITLE
Error while refreshing metadata index

### ISSUE THREAD

**Issue by IvanRibakov** [joeferraro/MavensMate-Atom#251]
I'm using MavensMate-Atom (v0.0.24) with Atom editor(1.0.11) on Mac OS X Yosemite 10.10.5.

I have created a fresh project and subscribed to a subset of metadata initially. Now that I attempt to subscribe to all available metadata items I get following error when trying to refresh project metadata:

`Could not index children/folders for CaseSharingRules: ENOENT: no such file or directory, lstat '/var/folders/11/5b3bk7b12yq7fp5qdy_vj0zr0000gn/T/mm_11584-398-to1k9h/unpackaged/caseSharingRules'`

Log output: https://www.dropbox.com/s/2url1jfri5qo20z/mavensmate.log.zip?dl=1

Steps to reproduce:
1. Navigate to new project screen
2. Subscribe to default metadata items
3. Create project
4. Navigate to project "Edit" screen
5. Select all available metadata items in "Advanced" tab
6. Navigate to "Project Metadata" tab and click "Refresh"

**UPDATE (07/09)**
Removing all *SharingRule metadata items from subscription has solved the problem. However as soon as any of them is added to the subscription list, metadata refresh begins to fail again with the error above.

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
