### ISSUE TITLE
Deploy resource bundle changes the zip folder structure

### ISSUE THREAD

**Issue by Avinava** [joeferraro/MavensMate-Atom#253]
This is something seems to be affecting only MavensMate for atom and was working fine in MM for Sublime.

Basically if we have a static resource with the name "MyZip.resource" , if deployed using the MM deploy resource bundle creates a Folder MyZip inside it.

Steps
-

- Create a zip file with no folder inside name it "MyZip" (upload the same to sf)
- Create resource bundle by right clicking the zip file, it creates a folder MyZip.resource
- Right click the same and deploy the bundle, it will add a folder with the name MyZip inside the original file , with all the content inside it

Platform : Mac OS X 10.10.5
MM Version : 0.0.24

**Comment by joeferraro** [comment]
this has been resolved in the mavensmate core and in 1.0.0 of mm for atom (available now), you should no longer encounter this issue.
