### ISSUE TITLE
Create Sandbox project unavailable for MM-Atom

### ISSUE THREAD

**Issue by ajitbhalla** [joeferraro/MavensMate-Atom#259]
![screen shot 2015-09-18 at 4 21 52 pm](https://cloud.githubusercontent.com/assets/14354492/9973050/67fca8d2-5e21-11e5-8659-387e5a1a8415.png)

How to create a MM (Atom) project for a Salesforce Sandbox org? The only options shown are Production & Development.

Is there a place to change the config / login url? Also what about orgs with custom login url?

**Comment by joeferraro** [comment]
mm for atom 1.0.0 is now dependent on mavensmate-app, which has all the environment options you need https://github.com/joeferraro/mavensmate-app/releases

<img width="639" alt="mavensmate" src="https://cloud.githubusercontent.com/assets/54157/9984530/0d4c163a-5fe7-11e5-8517-4e95da8e4b9c.png">
