### ISSUE TITLE
Cannot Install due to Git not being found

### ISSUE THREAD

**Issue by Saul3d** [joeferraro/MavensMate-Atom#261]
Tried installing Mavensmate via atoms' install package window and I keep getting this message.  I do have Git installed and the path environment variable set.

Installing “MavensMate-Atom@0.0.24” failed.Hide output…
Failed to install mavensmate-atom because Git was not found.

The mavensmate-atom package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

Run apm -v after installing Git to see what version has been detected.

Using:
Mac 10.10.5
Atom 1.0.11

**Comment by jeancdc** [comment]
Same problem here. When I run ```apm -v```, Git is however well detected.

I use:
- Mac OS X 10.10.5
- Atom 1.0.15
- Git 2.5 added in path environment variable

**Comment by jeancdc** [comment]
I still have the problem with MavensMate 1.0.3:
```
Installing “MavensMate-Atom@1.0.3” failed.
Failed to install mavensmate-atom because Git was not found.

The mavensmate-atom package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

Run apm -v after installing Git to see what version has been detected.
```

I have installed MavensMate-app and running it before installing the plugin.

**Comment by joeferraro** [comment]
@jeancdc I'm sorry that you're experiencing this issue, however, this is a local machine/apm issue, not a mavensmate-atom issue. You may try this atom thread: https://discuss.atom.io/t/unmet-git-dependency/14707

Good luck and let me know whether I can be of any additional assistance.

**Comment by jeancdc** [comment]
OK, launching Atom by the terminal with the command ```atom --safe``` before installing the plugin works. Thanks!

**Comment by joeferraro** [comment]
@jeancdc :+1:
