### ISSUE TITLE
CompileDelegate requires a valid project instance and an array of paths to compile.

### ISSUE THREAD

**Issue by aluukka** [joeferraro/MavensMate-Atom#263]
I just updated to MavensMate.app and MavensMate-Atom 1.0 and I cannot save files to Salesforce, or refresh them from Salesforce.

Saving gives this:
> CompileDelegate requires a valid project instance and an array of paths to compile.
{
  "id": "00f37b20-6038-11e5-8dd2-69435d5f71f0",
  "complete": true,
  "operation": "compile-metadata",
  "error": "CompileDelegate requires a valid project instance and an array of paths to compile.",
  "stack": "Error: CompileDelegate requires a valid project instance and an array of paths to compile.\n    at new CompileDelegate (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/compile.js:29:11)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/metadata/compile-metadata.js:24:27\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Command.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/metadata/compile-metadata.js:22:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:363:21\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Client.executeCommandForProject (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:341:10)\n    at UIServer.executePostHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/ui/server.js:104:10)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:100:13)\n    at Route.dispatch (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:81:3)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)",
  "promiseId": "00f06de0-6038-11e5-b153-fbbe260d9e45"
}

Refresh gives: 
Unable to parse the command's result. This really should not happen, so please generate a log and create a GitHub issue (please search before creating new issues!)
{
  "id": "46a483d0-6038-11e5-8dd2-69435d5f71f0",
  "complete": true,
  "operation": "refresh-metadata",
  "error": "Cannot read property 'path' of undefined",
  "stack": "TypeError: Cannot read property 'path' of undefined\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/metadata/refresh-metadata.js:28:52\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Command.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/metadata/refresh-metadata.js:24:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:363:21\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Client.executeCommandForProject (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:341:10)\n    at UIServer.executePostHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/ui/server.js:104:10)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:100:13)\n    at Route.dispatch (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:81:3)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:235:24",
  "promiseId": "469fa1d0-6038-11e5-b153-fbbe260d9e45"
}

Atom 1.0.15 MavensMate 1.0.0 OSX 10.10.5

**Comment by joeferraro** [comment]
@aluukka can you please provide specific steps to reproduce?

**Comment by aluukka** [comment]
it looks like it was a problem with a specific project which wouldn't open after the update. I recreated the project and refreshed its .git and the problem seems to be fixed

The failing project would not update the left-hand menu, which only contained the item Settings
