### ISSUE TITLE
Atom prompting for 1.0.2

### ISSUE THREAD

**Issue by nwoolls** [joeferraro/MavensMate-Atom#264]
Atom is only showing updates to 1.0.2, which does not exist. From following commits it seems like maybe just a mis-labeled version, but it also seems to have gotten into the Atom updates.

```
Updating to “MavensMate-Atom@1.0.2” failed.Hide output…
Unable to download https://www.atom.io/api/packages/mavensmate-atom/versions/1.0.2/tarball: 404
```

**Comment by joeferraro** [comment]
@nwoolls thx for the report, i've pushed 1.0.3 to fix the apm version issue
