### ISSUE TITLE
Menu items open Home screen in MavensMate-app (if window was closed)

### ISSUE THREAD

**Issue by nwoolls** [joeferraro/MavensMate-Atom#265]
This is on OS X. Clicking the Metadata menu items, e.g. to create a new Apex Class or Trigger, says it is opening the requested UI, but seems to just go to the Home screen in the MavensMate-app.

```
[September 21st 2015, 12:49:01 pm]
> Opening new Apex Class UI
> Success
{
  "id": "a8ed42f0-6080-11e5-88cb-ad3f78120a3d",
  "complete": true,
  "operation": "new-metadata",
  "result": {
    "message": "Success"
  },
  "promiseId": "a8eaf900-6080-11e5-a3de-916b87f4a86f"
}
```

*This only seems to occur if the MavensMate window was previously closed with the app still running.*

Clicking the Metadata menu item a second time does in fact show the UI for creating new metadata.

**Comment by nwoolls** [comment]
In hindsight this may be better suited for the MavensMate-app repo / issues.

**Comment by ralphcallaway** [comment]
@nwoolls yep, it's already in there https://github.com/joeferraro/MavensMate-app/issues/14
