### ISSUE TITLE
Version 1.0.3 does not work 

### ISSUE THREAD

**Issue by lnslevin** [joeferraro/MavensMate-Atom#270]
After I updated to version 1.0.3 MavensMate with Atom version 1.0.15 I can no longer use MavensMate.  I can open the MavensMate window however, it does not do anything when I click on things like Settings>Global Settings or Project>Open Project.  With Open Project it will show the drop down for the projects list but no projects are found, though there should be existing projects listed.

**Comment by joeferraro** [comment]
It's likely you're encountering this issue: https://github.com/joeferraro/MavensMate-Atom/issues/268#issuecomment-142337293

the workaround is to open the settings menu in mavensmate-app and set up your workspace
