### ISSUE TITLE
Global Setting not display anything 

### ISSUE THREAD

**Issue by Saul3d** [joeferraro/MavensMate-Atom#271]
Mac OSX - 10.10.5
Atom - 1.0.15
Mavensmate 1.0.4

When I click on Global setting nothing happens!  No error is logged.  Nothing.  I opened up the developer tool and this is what I see.

adapter.coffee:36 executing command via core adapter: 
adapter.coffee:37 Object {command: "open-settings", commandDefinition: Object, args: Object, payload: Object}
adapter.coffee:62 executing MavensMate command Object {method: "POST", url: "http://localhost:56248/execute?command=open-settings&async=1", headers: Object, body: "{"args":{"ui":true}}"}
panel-view-item.coffee:89 .....
panel-view-item.coffee:90 open-settings
panel-view-item.coffee:91 Object {command: "open-settings", commandDefinition: Object, args: Object, payload: Object, promiseId: "34d08cc0-61f6-11e5-9abc-2b2ec6229650"}
panel-view-item.coffee:103 Opening settings UI
adapter.coffee:65 REQUEST CALLBACK
adapter.coffee:66 Error: connect ECONNREFUSED 127.0.0.1:56248
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)
adapter.coffee:67 undefined
adapter.coffee:68 undefined
adapter.coffee:71 oh no --->
adapter.coffee:74 Error: Error reaching local MavensMate server
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)
panel-view.coffee:110 panel-notify-finish
panel-view.coffee:111 Object {command: "open-settings", commandDefinition: Object, args: Object, payload: Object, promiseId: "34d08cc0-61f6-11e5-9abc-2b2ec6229650"}
panel-view.coffee:112 Error: Error reaching local MavensMate server
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)
panel-view.coffee:121 panel view picked up an event!
panel-view.coffee:122 Object {command: "open-settings", commandDefinition: Object, args: Object, payload: Object, promiseId: "34d08cc0-61f6-11e5-9abc-2b2ec6229650"}
panel-view.coffee:123 Error: Error reaching local MavensMate server
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)
panel-view-item.coffee:63 updating panel item as a result of command ====>
panel-view-item.coffee:64 Object {command: "open-settings", commandDefinition: Object, args: Object, payload: Object, promiseId: "34d08cc0-61f6-11e5-9abc-2b2ec6229650"}
panel-view-item.coffee:65 Error: Error reaching local MavensMate server
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)
parsers.coffee:344 determing parser for command
parsers.coffee:345 open-settings
parsers.coffee:346 Object {command: "open-settings", commandDefinition: Object, args: Object, payload: Object, promiseId: "34d08cc0-61f6-11e5-9abc-2b2ec6229650"}
parsers.coffee:365 parser is: 
parsers.coffee:366 CommandParser(command, params, result)
parsers.coffee:21 CommandParser parsing ... -->
parsers.coffee:22 Error: Error reaching local MavensMate server
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)
panel-view.coffee:134 [div.mavensmate.mavensmate-output.tool-panel.panel-bottom.native-key-bindings.resize, element: div.mavensmate.mavensmate-output.tool-panel.panel-bottom.native-key-bindings.resize, resizeHandle: jQuery.fn.init[1], myHeader: jQuery.fn.init[1], btnViewErrors: jQuery.fn.init[1], viewErrorsIcon: jQuery.fn.init[1]…]

**Comment by joeferraro** [comment]
Do you have mavensmate-app running?

**Comment by Saul3d** [comment]
Yeah!  It's enabled!

**Comment by joeferraro** [comment]
What version of mavensmate-app are you running?

**Comment by Saul3d** [comment]
1.0.4

**Comment by joeferraro** [comment]
1.0.4 is the plugin version. v1+ of MavensMate for Atom requires the MavensMate-app program (see install instructions https://github.com/joeferraro/MavensMate-Atom#installation)

**Comment by Saul3d** [comment]
that was it thanks! Don't know how I missed that!

**Comment by Saul3d** [comment]
I am however getting a error now - 
Failed to update mm_workspace: Unexpected token

**Comment by Saul3d** [comment]
nevermind stupid mistake, thanks again.

**Comment by joeferraro** [comment]
cool, no worries
