### ISSUE TITLE
Cannot Update/Install

### ISSUE THREAD

**Issue by jdickertBHTP** [joeferraro/MavensMate-Atom#272]
Since about mid week last week, I have been unable to Update the Mavensmate Package.  Today, I uninstalled, and now I am unable to install.
![screen shot 2015-09-23 at 9 48 54 am](https://cloud.githubusercontent.com/assets/11069678/10048454/8c3a63aa-61d8-11e5-950b-9714c914e9db.png)

**Comment by joeferraro** [comment]
this looks like a local machine issue, have you tried: http://i-broke-it.blogspot.com/2013/10/fixing-xcrun-error-invalid-active.html

**Comment by jdickertBHTP** [comment]
Wow -- my fault!  Apologies!

**Comment by joeferraro** [comment]
no worries, cheers. :+1:
