### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Saul3d** [joeferraro/MavensMate-Atom#274]
Everytime I start mavensmate I get the following alert boxes.

<img width="418" alt="screen shot 2015-09-25 at 10 18 47 am" src="https://cloud.githubusercontent.com/assets/1847649/10224044/cada74fc-6821-11e5-8e49-afd245610a89.png">
<img width="422" alt="screen shot 2015-09-28 at 8 46 40 am" src="https://cloud.githubusercontent.com/assets/1847649/10224045/ccd7c4ee-6821-11e5-9f08-97b841871711.png">

**Comment by joeferraro** [comment]
Are you behind a firewall/using a proxy?

**Comment by Saul3d** [comment]
Yes I am, but I was getting a different alert message when I wan't behind a firewall.  Just tried to launch Mavensmate outside of the firewall and everything appears to work.  Sorry for the false alarm.

**Comment by joeferraro** [comment]
no worries whatsoever. the javascript popup is actually a bug, will be patching this week
