### ISSUE TITLE
New metadata dialogs don't open modally in Atom 

### ISSUE THREAD

**Issue by frizzy75** [joeferraro/MavensMate-Atom#275]
Whenever I attempt to create new metadata, e.g. Apex class, within Atom instead of Atom displaying a modal view, it launches MavensMate.app (v.0.0.7). Same for editing global settings.

Am I missing something? Why don't I see the nice modal dialogs as demonstrated in the Dreamforce video? http://dreamforce.vidyard.com/watch/jUWc75nrLQ1KMFWf72m4Nw

Thanks

**Comment by joeferraro** [comment]
modals have gone away for many reasons, mostly surrounding plugin stability. you can always install a previous version manually via `apm` e.g. https://github.com/joeferraro/MavensMate-Atom/releases/tag/v0.0.24
