### ISSUE TITLE
Changes to *-meta.xml files do not cause save to server

### ISSUE THREAD

**Issue by dsharrison** [joeferraro/MavensMate-Atom#280]
When editing a *-meta.xml file to accomplish something like changing the Salesforce API version, saving the *-meta.xml file does not trigger a compile. The current workaround is to force a compile of the associated class or page, which will bring the changes to the *-meta.xml file along with it.

Mavensmate.app version: 0.0.9
Mavensmate-atom version: 1.0.6
Atom version: 1.0.19

**Comment by jperro** [comment]
This also blocks the ability to use Atom to delete a production Apex class since changing the meta data status tag doesn't compile. When trying to compile both the class and the meta data file I'm getting: `"ErrorMsg": "Can't alter metadata in an active org"`

**Comment by jperro** [comment]
@dsharrison can you comment a bit more on the workaround?

**Comment by dsharrison** [comment]
@jperro I develop primarily as an ISV, so I have not encountered that issue when trying to save against a production org. I am not sure if Salesforce checks for a diff when editing files directly against a production environment, but have you tried saving the class using both the tooling and metadata APIs?
