### ISSUE TITLE
Introduce or respect Soft Tabs setting

### ISSUE THREAD

**Issue by nwoolls** [joeferraro/MavensMate-Atom#281]
It seems all Metadata from templates have Hard Tabs regardless of the editor's ```Soft Tabs``` setting. In addition there are ```Soft Wrap``` but no ```Soft Tab``` settings for Apex. Addressing this either way would be great.

**Comment by thvd** [comment]
:+1, indeed that will be great!

**Comment by iDev0urer** [comment]
Not saying this shouldn't be added, but Salesforce recommends that you use hard tabs in all of your classes, pages, etc because every tab and space counts against your limit. While in any other case soft tabs are the better choice, on Salesforce they are not
