### ISSUE TITLE
Errors remain after a compile resolves the error

### ISSUE THREAD

**Issue by loganm** [joeferraro/MavensMate-Atom#289]
Steps to reproduce:
1. Create a problem in a class and compile it (e.g. type some gibberish)
2. Error is captured in error tab, and error count at bottom right goes up
3. Resolve the problem and compile again

Expected:
The error is removed from the error tab
The error count at the bottom right is reduced

Actual:
The error remains in the error tab
The error count does not reduce

**Comment by ejmunson** [comment]
I'm experiencing this same issue, I've just started using the plugin and can't seem to get the error counter to decrement correctly without restarting Atom.

OSX 10.11.5
MavensMate-app v0.0.10
Atom 1.8.0
MavensMate-Atom v1.0.7
