### ISSUE TITLE
Automatically start MavensMate-app when Atom opens

### ISSUE THREAD

**Issue by matthewjmink** [joeferraro/MavensMate-Atom#291]
The Sublime Text plugin provides a setting called `mm_start_mavensmate_app` to automatically start the MavensMate companion app when Sublime is opened. This is very handy, but I cannot seem to find that setting in Atom anywhere. Could you please add this feature?

**Comment by iDev0urer** [comment]
#324 partially resolves this by adding a button to the MavensMate panel that launches the App
