### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by jdr0dn3y** [joeferraro/MavensMate-Atom#294]
Started getting the following error from Atom / MM while entering apex:remoteObjectField items.

I think MM has an issue with Visualforce Remote Objects.
``` HTML
<apex:remoteObjects>
  <apex:remoteObjectModel fields="commaSeparatedFields" jsShorthand="objectShortName" name="objectAPIName">
    <apex:remoteObjectFields jsShorthand="fieldShortName" name="fieldAPIName" />
  </apex:remoteObjectModel>
</apex:remoteObjects

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v1.0.7


### Stack Trace

Uncaught TypeError: Cannot read property 'attributes' of undefined

```
At /Users/justin/.atom/packages/MavensMate-Atom/lib/autocomplete/providers.coffee:298

TypeError: Cannot read property 'attributes' of undefined
    at Object.VisualforceTagProvider.getAttributeValues (/Users/justin/.atom/packages/MavensMate-Atom/lib/autocomplete/providers.coffee:298:35)
    at Object.VisualforceTagProvider.getAttributeValueCompletions (/Users/justin/.atom/packages/MavensMate-Atom/lib/autocomplete/providers.coffee:237:21)
    at Object.VisualforceTagProvider.getSuggestions (/Users/justin/.atom/packages/MavensMate-Atom/lib/autocomplete/providers.coffee:76:23)
    at /opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  3x -1:03.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:01.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:01.6.0 core:paste (atom-text-editor.editor.is-focused)
     -1:01.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:47.9.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:33.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  8x -0:24.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:20.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:16.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.9.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:06.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "projectHome": "/Users/justin/source",
    "disabledPackages": [
      "fonts"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "MavensMate-Atom": {
    "mm_panel_height": 224
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v1.0.7
color-picker, v2.0.13
file-icons, v1.6.12
github-notifications, v0.1.1
github-utils, v0.7.0
highlight-selected, v0.11.1
jira-issue-search, v0.2.2
language-mongodb, v0.3.1
language-swift, v0.4.0
minimap, v4.16.2
minimap-highlight-selected, v4.3.1
monokai, v0.18.0
pigments, v0.19.0
wakatime, v5.0.1

# Dev
No dev packages
```

**Comment by jdr0dn3y** [comment]
It appears to only happen when you use single quotes ``` ' ```` instead of double quotes ``` " ``

**Comment by jclark-dot-org** [comment]
Not limited to apex:remoteObjectField; I'm seeing this using single quotes on a div, e.g., 

    <div class='  

I get the exception when I type the single quote in the line above.

**Comment by mkeasling** [comment]
I am still seeing this error all the time.  ```<div class='``` causes it.  :(
