### ISSUE TITLE
Unable to Refresh Entire Project From Server

### ISSUE THREAD

**Issue by naveenila1221** [joeferraro/MavensMate-Atom#297]
I am unable to refresh entire project. When somebody created new files in the project using some other editors, unable to refer those files. There is no option to refresh the entire project, we have only one option i.e., Delete From Server

**Comment by Kagool** [comment]
Cleaning the project will pull any new files from the server
| Mavens Mate | Project | Clean Project |

**Comment by naveenila1221** [comment]
Its Working. Thank you!
