### ISSUE TITLE
Could not open in editor - Atom/MM

### ISSUE THREAD

**Issue by ddawson90** [joeferraro/MavensMate-Atom#302]
I have newly installed Atom and MM in OSX and have the atom executable configured with the following setting:
```
{
  "windows": "C:\\Program Files\\Atom\\Atom.exe",
  "linux": "/usr/bin/atom",
  "osx": "/Applications/Atom.app/Contents/Resources/app/apm/bin/apm"
}
```

When I try and create a new class from Atom it takes me too MM and upon creation I get the following error:

> Could not open in editor

Any idea what could be causing this? I couldn't find much information on this error but I may have the installation configuration wrong?

**Comment by iDev0urer** [comment]
I don't own a Mac anymore so I cant test this, but it looks like your osx config is linking to `apm` instead of Atom. It should either be `/usr/local/bin/atom` or maybe `~/Applications/Atom.app`
