### ISSUE TITLE
Try to detect MavensMate-App again if it's not running

### ISSUE THREAD

**Issue by boxfoot** [joeferraro/MavensMate-Atom#306]
1. Start Atom (without MavensMate-App running)
2. Get error that it can't find MavensMate-App
3. Start MavensMate-App
4. Try to save something to server

Expected result:  Notices that MavensMate-App is now running and saves to Salesforce  
Actual Result: Nothing happens.  Need to exit and restart Atom to connect to MavensMate-App

```
MM version 0.0.11-beta1  
Atom version 1.6.2  
MM-Atom version 1.0.7
```

**Comment by iDev0urer** [comment]
This should be fixed in #323. Just waiting for my changes to be merged in
