### ISSUE TITLE
Can't set up a keybinding for compile to server

### ISSUE THREAD

**Issue by boxfoot** [joeferraro/MavensMate-Atom#308]
I don't like auto-building -- I prefer to manually compile when I'm ready.   So I turned off autobuilding and tried to make a manual keystroke, but it's not working...

Here is my keybinding, binding compile to `mavensmate:compile`

```cson
'body':
  'ctrl-shift-S': 'mavensmate:compile'
```

In this screenshot, you can see that atom correctly identifies the keystroke and triggers the command:

![image](https://cloud.githubusercontent.com/assets/487130/14323940/63ba8298-fbe8-11e5-8960-94a2c8651940.png)

BUT you can also see in the MavensMate pane that nothing is happening -- the compile isn't actually being triggered...  Any idea what's happening or how to fix it?

**Comment by iDev0urer** [comment]
@boxfoot Try changing it from `mavensmate:compile` to `mavensmate:compile-metadata`

**Comment by boxfoot** [comment]
That worked -- thanks!
