### ISSUE TITLE
Windows: get atom was not found in list of supported editors issue

### ISSUE THREAD

**Issue by lance-shi** [joeferraro/MavensMate-Atom#309]
When creating new project for Salesforce, I am getting atom was not found in list of supported editors issue. In my global setting, I have set the Atom executable location to the right location. In mm_atom_exec_path, I have set "windows" to be "C:\\Program Files (x86)\\atom\\app-1.6.2\\atom.exe", which is copied from appData location which is the default Atom location. Also tried with the appData location which didn't work either. Both location proved to be working in cmd. 

OS: Windows 7, x64. 
mm version: v0.0.11-beta1

**Comment by viraj89** [comment]
Even I had this issue, but later got it fixed. 
Are you sure about the installed path location found at the Program Files location? 
Because for me by default it got installed at this path- 

`C:\Users\YOURNAME\AppData\Local\atom\app-1.6.2\atom.exe` 

MM requires the executable file which resides inside `app-1.6.2` folder. 
Add this above path in your global setting in MM and re-try.

**Comment by lance-shi** [comment]
@viraj89 It is the location you mentioned. I tried that before and it did not work for me. I thought it was folder issue so I copied the whole folder into program files and retried. And still no luck.

**Comment by viraj89** [comment]
@lance-shi In that case, you setting the path as - ` "windows" to be "C:\Program Files (x86)\atom\app-1.6.2\atom.exe"` won't work. 

Are you able to see this? 
![atom1](https://cloud.githubusercontent.com/assets/9387490/14451788/5b9506d8-00a7-11e6-9a8b-08c4362fa0df.jpg)

If you are able to see this, your 50% job is done, the yet 50% is the executable path which needs to be set. Pls recheck once again.

**Comment by lance-shi** [comment]
@viraj89 No. I can't see that. But I just retried without changing anything and it miraculously worked for me! I am not sure why.

**Comment by viraj89** [comment]
@lance-shi That's great it helped you and got it working. I'm think I'm sure its about the executable path that needs to be set.
