### ISSUE TITLE
Not able to create new project in atom ide on windows 8 machine

### ISSUE THREAD

**Issue by deref** [joeferraro/MavensMate-Atom#310]
IDE: Atom 1.8.0-beta1
Machine: Windows 8 (64 bit)
MavensMate: MavensMate-app-v0.0.11-beta1-win-x64-setup

Not able to create a new project from atom .I always get the following error:-

'atom was not found in list of supported editors. Please check your global settings to ensure the editor path for atom is configured correctly.' Although the path is correctly set in windows.

The project files get downloaded in the specified workspace. It is working in case of sublime text 3.
Only in case of Atom I am getting this error. I have been trying for the past 2 days, but no luck . I really want to migrate to using Atom and ditch sublime. 

What can i do to fix this.? Please help!!

![maven_raven](https://cloud.githubusercontent.com/assets/8383926/14590788/41fddea6-0521-11e6-8be9-753a62e7f337.PNG)

**Comment by vppravi93** [comment]
Same is happening for me :-(

**Comment by rmcneill24** [comment]
Same here.

**Comment by joeferraro** [comment]
What's the value of your "mm_atom_exec_path" setting in mm-app?

**Comment by deref** [comment]
[
  "C:\\Users\\gautamkumar\\AppData\\Local\\atom\\app-1.7.0\\atom.exe"
]

**Comment by joeferraro** [comment]
Are you escaping your path slashes? Because what you've just pasted is not valid JSON

<img width="487" alt="mavensmate" src="https://cloud.githubusercontent.com/assets/54157/15292871/4a46da0c-1b53-11e6-98f2-862a21715132.png">

**Comment by joeferraro** [comment]
@deref and I assume you've verified that this path does indeed exist?

**Comment by deref** [comment]
Hi.
Yes i am escaping the path slashes, yes this path exists

**Comment by deref** [comment]
I have tried using the zip version of atom and changed the path to 

[
  "C:\\Atom Beta\\atom.exe"
]

But still no luck. I got the same error

**Comment by rmcneill24** [comment]
Thanks for the quick response. It is set to:

"C:\\Users\\rmcneill\\Desktop\\MavensMate"

On Mon, May 16, 2016 at 10:42 AM, Joe Ferraro <notifications@github.com>
wrote:

> What's the value of your "mm_atom_exec_path" setting in mm-app?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-Atom/issues/310#issuecomment-219442864>
>



-- 
Mr. McNeill

Psalm 91:1

He who dwells in the shelter of the Most High will rest in the shadow of
the Almighty.

**Comment by rmcneill24** [comment]
Sorry. I gave you the wrong info. (mm_atom_exec_path) is
  "windows": "C:\\Program Files\\Atom\\Atom.exe",

On Mon, May 16, 2016 at 10:42 AM, Joe Ferraro <notifications@github.com>
wrote:

> What's the value of your "mm_atom_exec_path" setting in mm-app?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-Atom/issues/310#issuecomment-219442864>
>



-- 
Mr. McNeill

Psalm 91:1

He who dwells in the shelter of the Most High will rest in the shadow of
the Almighty.

**Comment by joeferraro** [comment]
I was able to reproduce on a Windows VM, but not sure the root of the issue. As a workaround, I was able to set my `mm_atom_exec_path` value as a string (versus an object):

![windows_8](https://cloud.githubusercontent.com/assets/54157/15293568/996ff8c2-1b56-11e6-8a82-a3fbb692b221.png)

**Comment by deref** [comment]
@joeferraro  this is still not working on my machine.

**Comment by joeferraro** [comment]
Can you post the contents of your `C:\Users\<user>\AppData\Roaming\MavensMate\mavensmate-config.json` file?

**Comment by deref** [comment]
@joeferraro 

{
  "mm_workspace": [
    "/tc/work"
  ],
  "mm_api_version": "36.0",
  "mm_compile_check_conflicts": true,
  "mm_download_categorized_test_logs": false,
  "mm_timeout": 600,
  "mm_default_subscription": [
    "ApexClass",
    "ApexComponent",
    "ApexPage",
    "ApexTrigger",
    "StaticResource"
  ],
  "mm_ignore_managed_metadata": true,
  "mm_use_keyring": true,
  "mm_compile_with_tooling_api": true,
  "mm_subl_location": [
    "C:\\Program Files\\Sublime Text 3\\sublime_text.exe"
  ],
  "mm_atom_exec_path": "C:\\Users\\gautamkumar\\AppData\\Local\\atom\\app-1.7.3\\atom.exe",
  "mm_log_location": "C:\\\\tc\\\\work\\\\logs",
  "mm_log_level": "DEBUG",
  "mm_play_sounds": true,
  "mm_template_location": "remote",
  "mm_template_source": "joeferraro/MavensMate-Templates/master",
  "mm_apex_file_extensions": [
    ".page",
    ".component",
    ".cls",
    ".object",
    ".trigger",
    ".layout",
    ".resource",
    ".remoteSite",
    ".labels",
    ".app",
    ".dashboard",
    ".permissionset",
    ".workflow",
    ".email",
    ".profile",
    ".scf",
    ".queue",
    ".reportType",
    ".report",
    ".weblink",
    ".tab",
    ".letter",
    ".role",
    ".homePageComponent",
    ".homePageLayout",
    ".objectTranslation",
    ".flow",
    ".datacategorygroup",
    ".snapshot",
    ".site",
    ".sharingRules",
    ".settings",
    ".callCenter",
    ".community",
    ".authProvider",
    ".customApplicationComponent",
    ".quickAction",
    ".approvalProcess",
    ".html"
  ],
  "mm_http_proxy": "",
  "mm_https_proxy": "",
  "mm_mavensmate_app_path": [
    "C:\\Program Files\\MavensMate\\MavensMate.exe"
  ],
  "mm_purge_on_delete": true,
  "mm_legacy_compile": false,
  "mm_use_browser_as_ui": false
}

**Comment by rmcneill24** [comment]
I think this is it. I didn't see the mavensmate-config,json file in that
path.

  "MavensMate-Atom":
    mm_panel_height: 288
  core:
    disabledPackages: [
      "git-plus"
    ]
  editor:
    invisibles: {}
  "exception-reporting":
    userId: "62a46b89-c601-7803-99c3-84ce8ed1a857"
  minimap:
    absoluteMode: true
    adjustAbsoluteModeHeight: true
  welcome:
    showOnStartup: false
".apex.source":
  editor:
    softWrap: false
".log.source":
  editor:
    showIndentGuide: false


On Mon, May 16, 2016 at 11:34 AM, Joe Ferraro <notifications@github.com>
wrote:

> Can you post the contents of your
> C:\Users\<user>\AppData\Roaming\MavensMate\mavensmate-config.json file?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-Atom/issues/310#issuecomment-219457397>
>



-- 
Mr. McNeill

Psalm 91:1

He who dwells in the shelter of the Most High will rest in the shadow of
the Almighty.

**Comment by deref** [comment]
@joeferraro any points to what i can do to make it right in the config file and be able to create a new project in atom?

**Comment by deref** [comment]
Hi @joeferraro  Is this bug fixed?

**Comment by joeferraro** [comment]
We've moved MavensMate issue tracking to our [central issues repository](https://github.com/joeferraro/MavensMate/issues) because there are more than 5 Github MavensMate repositories and it's hard for contributors to keep track of the issues across all of those projects. There's also been a significant amount of development in the last 6 months and it's hard for us to know which bugs were addressed and which ones remain valid (some are more than 3 years old). If you believe your issue is still valid and unresolved, please feel free to create a new issue in the central repository and reference the original ticket in your report.  Thank you for your understanding!

-Joe
