### ISSUE TITLE
Error reaching local MavensMate server. Please ensure MavensMate-app

### ISSUE THREAD

**Issue by basakpratik** [joeferraro/MavensMate-Atom#326]
Whenever I am trying to create a new project using Mavensmate I am getitng this error message.

> Opening new project UI
> Error reaching local MavensMate server. Please ensure MavensMate-app (https://github.com/joeferraro/mavensmate-app) is installed and running.
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 56248,
  "rawStack": [
    {},
    {},
    {}
  ],
  "promiseId": "4737c9a0-2e3d-11e6-8efb-b35d33872b60",
  "success": false
}

Note: I am using Windows 10, just to let you know if the OS environment matters.

**Comment by iDev0urer** [comment]
Hope I'm not asking a dumb question here, but have you installed the MavensMate App? I've been running it on Windows 10 with no issues

**Comment by basakpratik** [comment]
The Mavesmate App is having some problem. I am not able to run the exe file. Whenever I am trying to execute the exe file, a console window opens up and closes down and thats it. So I checked the Windows platform, it said Windows 7/8. But you are running it on windows 10. Don't know the reason for this problem I am having.

Note: I am trying to set it up in another system of mine with Windows 7 in it, just to check whether the OS dependency from my end.

**Comment by iDev0urer** [comment]
What's the output of netstat -a -n -o | find "56248"

I wonder if you have something running on the port MavensMate is trying to use

**Comment by basakpratik** [comment]
How do I find out whether the port is already in use? I am getting no output when I use `netstat -a -n -o | find "56248"`

I have also attached a screenshot
![capture](https://cloud.githubusercontent.com/assets/10449831/15953308/213a3be8-2ee7-11e6-8f28-540ef1183705.PNG)
