### ISSUE TITLE
Bug report doesn't clear after successful compilation

### ISSUE THREAD

**Issue by gerryvandermolen** [joeferraro/MavensMate-Atom#327]
When there is a compilation error the bugs button (the one with the little bug on it) gets red and shows the number of errors. If you click on it, it shows you a very helpful table listing each error. But then once the errors disappear after a successful compilation the button nor the list of bugs clear out, the button is still on red showing the number of old bugs and the list still shows old errors. 

![image](https://cloud.githubusercontent.com/assets/20111061/16305660/34cd2a5e-3931-11e6-974b-9a378a30f68e.png)

**Comment by muchavie** [comment]
I'm hitting this problem on version 1.0.10 for Atom.
