### ISSUE TITLE
Cannot read property 'result' of null

### ISSUE THREAD

**Issue by rodrigoliberal** [joeferraro/MavensMate-Atom#332]
When i create a project using sublime the following error is triggered with this error message: **Cannot read property 'result' of null** I don't know the cause.

**Comment by prateekgoel1503** [comment]
Hi
Even I am facing the same issue. Can you please let me what's causing it and what's the fix.

**Comment by ptolemyrulz** [comment]
![image](https://cloud.githubusercontent.com/assets/588827/21657327/f9891e8e-d27e-11e6-905a-91d991fd23e5.png)

I'm experiencing the same issue with what I believe is the current Maven's Mate release.  My Desktop App says beta 6 but  package control says there are no new updates.  
Please advise.

**Comment by ptolemyrulz** [comment]
I installed the beta 7 version of Maven's Mate and it resolved this issue.  Thank you!
