### ISSUE TITLE
atom was not found in list of supported editors. Please check your global settings to ensure the editor path for atom is configured correctly.

### ISSUE THREAD

**Issue by vermaajit** [joeferraro/MavensMate-Atom#333]
I have tried multiple options to setup atom path but nothing is working. any idea how this is setup on mac?

**Comment by dsharrison** [comment]
Here are my settings that work with a default atom installation on OSX

![screen shot 2016-08-17 at 1 56 44 pm](https://cloud.githubusercontent.com/assets/9137905/17752914/d1349ec8-6482-11e6-8a1f-1c5de5a40bec.png)

**Comment by vermaajit** [comment]
Thanks for the quick response. I had the same settings by default and it did not work and then I modified path same way as for sublime but that did not work too.

**Comment by dsharrison** [comment]
Where do you have atom installed on your machine? You might also try installing the shell tools for atom (https://discuss.atom.io/t/open-file-project-from-terminal-command-line/1305). I have these installed but I am not sure if that has any impact on the file paths.

**Comment by saumyak** [comment]
Though it throws the error message , the file does get created - at least that's what happened to me
