### ISSUE TITLE
Preview broken on Atom 1.10.0

### ISSUE THREAD

**Issue by Krisa** [joeferraro/MavensMate-Atom#335]
While the plugin seems still functional, the panel looks now broken:
![image](https://cloud.githubusercontent.com/assets/1253866/18162134/46754db4-7035-11e6-9906-cab3a4b36535.png)

Possibly related to https://github.com/joeferraro/MavensMate-Atom/issues/334

**Comment by kbannon** [comment]
I'm having the same issue..

**Comment by kbannon** [comment]
Awesome thanks!

**Comment by Krisa** [comment]
thanks too :)
