### ISSUE TITLE
Deprecated selector in `MavensMate-Atom/styles/highlights.less`

### ISSUE THREAD

**Issue by jeancdc** [joeferraro/MavensMate-Atom#342]
In `MavensMate-Atom/styles/highlights.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .highlight,
atom-text-editor::shadow .highlight` => `atom-text-editor .highlight,
atom-text-editor.editor .highlight`

* `atom-text-editor .highlight.mm-compile-error-line .region,
atom-text-editor::shadow .highlight.mm-compile-error-line .region` => `atom-text-editor .highlight.mm-compile-error-line .region,
atom-text-editor.editor .highlight.mm-compile-error-line .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by kanedauy** [comment]
Receiving deprecation message because of this, running ver 1.0.10 (current ver)
