### ISSUE TITLE
Disabling MavensMate does not remove menu items or commands

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate-Atom#77]
When MavensMate is deactivated menu items (main menu and sidebar menus) still exist and commands are still accessible in the command palette. 

Need to figure out how to clean up menu items and commands when deactivating packages. It appears that upon re-enabling the package and calling a command two instances of the command are called.

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
